name: oishape_bm

channels:
  - defaults

dependencies:
  - python==3.10
  - pip
  - setuptools
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.11.0
  - bottler::nvidiacub
  - pytorch::torchaudio=0.11.0
  - pytorch::torchvision=0.12.0
