DATA_PRESET:
  CENTER_IDX: 9
  USE_CACHE: True
  N_RESAMPLED_OBJ_POINTS: 4096
  N_INTENTS: 2

DATASET:
  TRAIN:
    TYPE: OIShape
    DATA_SPLIT: train
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: ["use", "hold"]
    
  VAL:
    TYPE: OIShape
    DATA_SPLIT: val
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: ["use", "hold"]

  TEST:
    TYPE: OIShape
    DATA_SPLIT: test
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: "all"


TRANSFORM:
  TYPE: GrabNetTransformObject
  RAND_ROT: True
  RAND_DEG_STD: 10
  USE_ORIGINAL_OBJ_ROT: False
  BPS_BASIS_PATH: assets/GrabNet/bps.npz
  BPS_FEAT_TYPE: dists

MODEL:
  TYPE: GrabNet
  COARSE_NET:
    TYPE: CoarseIntentNetIntentEmbedEncode
    LATENTD: 16
    KL_COEF: 0.005
    VPE_PATH: "assets/GrabNet/verts_per_edge.npy"
    C_WEIGHT_PATH: "assets/GrabNet/rhand_weight.npy"
    PRETRAINED: checkpoints/intent/trigger_sprayer/CoarseIntentNetIntentEmbedEncode.pth.tar

  REFINE_NET:
    TYPE: RefineNet
    KL_COEF: 0.005
    VPE_PATH: "assets/GrabNet/verts_per_edge.npy"
    C_WEIGHT_PATH: "assets/GrabNet/rhand_weight.npy"
    PRETRAINED: checkpoints/grabnet_oishape/RefineNet.pth.tar
